'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { api, message, parseGame, Game } from '@/lib/api';
import { IssuePage, IssueDetail, parseIssuePage, parseIssueDetail } from '@/lib/issues';
import { IssueMetrics, IssueEvidence, SnapshotInfo } from '@/app/issue-components';
export function IssuesWorkspace({id,issueId,page,minSeverity="0"}:{id:string;issueId?:string;page:string;minSeverity?:string}){
  const [game,setGame]=useState<Game|null>(null),[data,setData]=useState<IssuePage|IssueDetail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController();
    async function load(){try{const [game,data]=await Promise.all([api(`games/${id}`,parseGame,{signal:controller.signal}),issueId?api(`games/${id}/issues/${issueId}?page=${encodeURIComponent(page)}`,parseIssueDetail,{signal:controller.signal}):api(`games/${id}/issues?page=${encodeURIComponent(page)}&minSeverity=${encodeURIComponent(minSeverity)}`,parseIssuePage,{signal:controller.signal})]);if(!controller.signal.aborted){setGame(game);setData(data);setError('');}}catch(e){if(!controller.signal.aborted)setError(message(e));}}
    void load();return()=>controller.abort();
  },[id,issueId,page,minSeverity,retry]);
  async function rebuild(){setBusy(true);setError('');try{await api(`games/${id}/issues/rebuild`,parseIssuePage,{method:'POST'});setRetry(v=>v+1);}catch(e){setError(message(e));}finally{setBusy(false);}}
  const path=`/games/${id}/issues${issueId?`/${issueId}`:''}`;
  return <><div className="workspace-nav"><Link href={`/games/${id}`}>← Reviews</Link>{issueId&&<Link href={`/games/${id}/issues`}>All issues</Link>}<Link href="/demo/issues">Synthetic demo</Link></div>
    <div className="page-heading"><div><div className="eyebrow">{game?.name??'GAME WORKSPACE'} · ISSUE INTELLIGENCE</div><h1>{data&&'issue'in data?data.issue.title:'Issues & evidence'}</h1></div>{!issueId&&<button className="primary" disabled={busy||!data} onClick={rebuild}>{busy?'Grouping…':'Rebuild issues'}</button>}</div>
    {error&&<div className="panel compact" role="alert"><p className="error">{error}</p><p className="muted">Previously displayed results may be stale.</p><button onClick={()=>setRetry(v=>v+1)}>Retry loading</button></div>}
    {!data&&!error&&<section className="panel" role="status">Loading issues…</section>}
    {data&&<><SnapshotInfo snapshot={data.snapshot}/>{'issue'in data?<section className="panel"><div className="eyebrow">{data.issue.category} · {data.issue.status}</div><IssueMetrics metrics={data.issue.metrics}/><h2>Source evidence</h2><p className="muted">Exact source snapshots used for this calculation.</p><IssueEvidence evidence={data.evidence}/></section>:<section className="panel"><div className="page-heading"><h2>{data.total} issues</h2><form className="filters" action={path}><div><label htmlFor="severity-filter">Minimum severity</label><select id="severity-filter" name="minSeverity" defaultValue={minSeverity}><option value="0">All issues</option><option value="75">High (75+)</option><option value="100">Critical (100)</option></select></div><button type="submit">Apply filter</button></form></div>{data.items.length===0?<p className="muted">{data.snapshot.eligibleReviews===0?'No current actionable analyses. Analyze reviews first, or explore the separate synthetic demo.':data.snapshot.builtAt?'No issues match this severity or page. Change the filter or return to the first page.':'Rebuild issues to group the available analyses.'}</p>:<div className="table-scroll issue-table"><table><thead><tr><th>Severity</th><th>Issue</th><th>Mentions</th><th>7-day trend</th><th>Confidence</th><th>Last seen</th></tr></thead><tbody>{data.items.map(issue=><tr key={issue.id}><td><span className={`severity-tag ${issue.metrics.severityScore>=75?'severity-high':''}`}>{issue.metrics.severityScore.toFixed(0)} / 100</span></td><td><Link href={`/games/${id}/issues/${issue.id}`}>{issue.title}</Link><small>{issue.category.replaceAll('_',' ')} · {issue.status}</small></td><td>{issue.metrics.mentionCount}</td><td>{issue.metrics.velocityPercent===null?'No baseline':`${issue.metrics.velocityPercent>0?'+':''}${issue.metrics.velocityPercent.toFixed(0)}%`}<small>{issue.metrics.recentMentions} vs {issue.metrics.previousMentions}</small></td><td>{Math.round(issue.metrics.confidence*100)}%</td><td>{new Date(issue.metrics.lastSeenAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section>}
    <nav className="pagination" aria-label={issueId?'Evidence pages':'Issue pages'}>{data.page>0&&<Link href={`${path}?page=${data.page-1}&minSeverity=${minSeverity}`}>Previous</Link>}<span>Page {data.page+1}</span>{(data.page+1)*data.size<data.total&&<Link href={`${path}?page=${data.page+1}&minSeverity=${minSeverity}`}>Next</Link>}</nav></>}
  </>;
}
