package com.playersignal.auth;
import com.playersignal.shared.ApiException;
import java.time.*;
import java.util.*;
import java.security.*;
import java.nio.charset.StandardCharsets;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/workspace")
public class WorkspaceController {
 public record InviteInput(String email,String role) {} public record TokenInput(String token) {} public record SwitchInput(UUID workspaceId) {} public record RoleInput(String role) {}
 private final JdbcTemplate jdbc;private final WorkspaceContext context;
 public WorkspaceController(JdbcTemplate jdbc,WorkspaceContext context){this.jdbc=jdbc;this.context=context;}
 private void accounts(){if(!context.enabled())throw new ApiException(409,"ACCOUNTS_DISABLED","Team membership requires account mode; local data stays in the local workspace.");}
 @GetMapping public Map<String,Object> get(){UUID id=context.current();String role=context.role();return Map.of("id",id,"name",jdbc.queryForObject("SELECT name FROM playersignal.workspace WHERE id=?",String.class,id),"role",role,"accountsEnabled",context.enabled(),"members",context.enabled()?jdbc.queryForList("SELECT u.id,u.email,m.role FROM playersignal.workspace_member m JOIN playersignal.app_user u ON u.id=m.user_id WHERE m.workspace_id=? ORDER BY u.email",id):List.of(),"workspaces",context.enabled()?jdbc.queryForList("SELECT w.id,w.name,m.role FROM playersignal.workspace_member m JOIN playersignal.workspace w ON w.id=m.workspace_id WHERE m.user_id=? ORDER BY w.name,w.id",context.user()):List.of(),"invites",role.equals("OWNER")?jdbc.queryForList("SELECT id,email,role,expires_at FROM playersignal.workspace_invite WHERE workspace_id=? AND accepted_at IS NULL AND expires_at>now() ORDER BY created_at DESC",id):List.of());}
 @PostMapping("/invites") @Transactional public Map<String,Object> invite(@RequestBody InviteInput input){
  accounts();context.requireOwner();if(input.email()==null||input.email().length()>254||!input.email().strip().matches("[^\\s@]+@[^\\s@]+\\.[^\\s@]+")||input.role()==null||!Set.of("ADMIN","MEMBER").contains(input.role()))throw new ApiException(400,"INVALID_INVITE","Enter a valid email and ADMIN or MEMBER role.");
  UUID workspace=context.current();jdbc.queryForObject("SELECT id FROM playersignal.workspace WHERE id=? FOR UPDATE",UUID.class,workspace);
  if(jdbc.queryForObject("SELECT count(*) FROM playersignal.workspace_invite WHERE workspace_id=? AND accepted_at IS NULL AND expires_at>now()",Long.class,workspace)>=10)throw new ApiException(422,"INVITE_LIMIT","Revoke an invite before creating another (limit 10).");
  byte[] bytes=new byte[32];new SecureRandom().nextBytes(bytes);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);UUID id=UUID.randomUUID();var expires=Instant.now().plusSeconds(7*86400);
  jdbc.update("INSERT INTO playersignal.workspace_invite(id,workspace_id,email,role,token_hash,expires_at) VALUES (?,?,?,?,?,?)",id,workspace,input.email().strip().toLowerCase(Locale.ROOT),input.role(),hash(token),java.sql.Timestamp.from(expires));return Map.of("id",id,"token",token,"expiresAt",expires);
 }
 @PostMapping("/invites/accept") @Transactional public Map<String,Boolean> accept(@RequestBody TokenInput input){
  accounts();if(input.token()==null||input.token().length()!=43)throw new ApiException(400,"INVALID_INVITE","Invalid invitation token.");
  var invite=jdbc.queryForList("SELECT * FROM playersignal.workspace_invite WHERE token_hash=? AND accepted_at IS NULL AND expires_at>now() FOR UPDATE",hash(input.token()));
  if(invite.isEmpty())throw new ApiException(404,"INVITE_NOT_FOUND","Invitation is invalid, expired or already used.");var row=invite.getFirst();var principal=context.principal(context.user());if(!principal.email().equals(row.get("email")))throw new ApiException(403,"INVITE_ACCOUNT","Sign in with the email address named in the invitation.");UUID workspace=(UUID)row.get("workspace_id");
  jdbc.queryForObject("SELECT id FROM playersignal.workspace WHERE id=? FOR UPDATE",UUID.class,workspace);if(jdbc.queryForObject("SELECT count(*) FROM playersignal.workspace_member WHERE workspace_id=?",Long.class,workspace)>=50)throw new ApiException(422,"MEMBER_LIMIT","This workspace has reached its 50-member limit.");
  jdbc.update("INSERT INTO playersignal.workspace_member(workspace_id,user_id,role) VALUES (?,?,?) ON CONFLICT DO NOTHING",workspace,principal.id(),row.get("role"));jdbc.update("UPDATE playersignal.app_user SET workspace_id=? WHERE id=?",workspace,principal.id());jdbc.update("UPDATE playersignal.workspace_invite SET accepted_at=now() WHERE id=?",row.get("id"));return Map.of("accepted",true);
 }
 @PostMapping("/invites/{id}/revoke") public Map<String,Boolean> revoke(@PathVariable UUID id){accounts();context.requireOwner();jdbc.update("UPDATE playersignal.workspace_invite SET expires_at=now() WHERE id=? AND workspace_id=? AND accepted_at IS NULL",id,context.current());return Map.of("revoked",true);}
 @PostMapping("/switch") public Map<String,Boolean> select(@RequestBody SwitchInput input){accounts();if(input.workspaceId()==null||jdbc.queryForObject("SELECT count(*) FROM playersignal.workspace_member WHERE workspace_id=? AND user_id=?",Long.class,input.workspaceId(),context.user())==0)throw new ApiException(404,"WORKSPACE_NOT_FOUND","Workspace unavailable.");jdbc.update("UPDATE playersignal.app_user SET workspace_id=? WHERE id=?",input.workspaceId(),context.user());return Map.of("switched",true);}
 @PostMapping("/members/{user}/role") public Map<String,Boolean> role(@PathVariable UUID user,@RequestBody RoleInput input){accounts();context.requireOwner();if(input.role()==null||!Set.of("ADMIN","MEMBER").contains(input.role()))throw new ApiException(400,"INVALID_ROLE","Choose ADMIN or MEMBER.");if(jdbc.update("UPDATE playersignal.workspace_member SET role=? WHERE workspace_id=? AND user_id=? AND role<>'OWNER'",input.role(),context.current(),user)!=1)throw new ApiException(404,"MEMBER_NOT_FOUND","Member not found or owner role is protected.");return Map.of("updated",true);}
 @PostMapping("/members/{user}/remove") @Transactional public Map<String,Boolean> remove(@PathVariable UUID user){accounts();context.requireOwner();UUID workspace=context.current();if(jdbc.update("DELETE FROM playersignal.workspace_member WHERE workspace_id=? AND user_id=? AND role<>'OWNER'",workspace,user)!=1)throw new ApiException(404,"MEMBER_NOT_FOUND","Member not found or owner cannot be removed.");jdbc.update("UPDATE playersignal.app_user SET workspace_id=(SELECT workspace_id FROM playersignal.workspace_member WHERE user_id=? AND role='OWNER' ORDER BY workspace_id LIMIT 1) WHERE id=? AND workspace_id=?",user,user,workspace);return Map.of("removed",true);}
 @GetMapping("/operations") public Map<String,Object> operations(){context.requireWrite();UUID workspace=context.current();return Map.of("imports",jdbc.queryForList("SELECT r.id,r.game_id,g.name,r.status,r.started_at,r.finished_at,r.error FROM playersignal.ingestion_run r JOIN playersignal.game g ON g.id=r.game_id WHERE g.workspace_id=? ORDER BY r.started_at DESC LIMIT 50",workspace),"analyses",jdbc.queryForList("SELECT r.id,r.game_id,g.name,r.status,r.processed,r.failed,r.started_at,r.error FROM playersignal.analysis_run r JOIN playersignal.game g ON g.id=r.game_id WHERE g.workspace_id=? ORDER BY r.started_at DESC LIMIT 50",workspace));}
 private String hash(String token){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(token.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
