'use client';
import {useEffect,useState} from 'react';
import {api,message} from '@/lib/api';
import {record,string} from '@/lib/workspace';
type Limits={plan:string;games:number;monthlyAttempts:number;reportsPerGame:number;seats:number};
type Price={plan:string;amount:number;currency:string;limits:Limits};
type Status={enabled:boolean;configured:boolean;webhookConfigured:boolean;limits:Limits;subscriptionStatus:string;prices:Price[]};
function limits(value:unknown):Limits{const d=record(value);for(const k of ['games','monthlyAttempts','reportsPerGame','seats'])if(!Number.isSafeInteger(d[k])||Number(d[k])<0)throw Error('Invalid plan limits');return {plan:string(d.plan),games:Number(d.games),monthlyAttempts:Number(d.monthlyAttempts),reportsPerGame:Number(d.reportsPerGame),seats:Number(d.seats)};}
function parse(value:unknown):Status{const d=record(value);if(typeof d.enabled!=='boolean'||typeof d.configured!=='boolean'||typeof d.webhookConfigured!=='boolean'||!Array.isArray(d.prices))throw Error('Invalid billing response');return {enabled:d.enabled,configured:d.configured,webhookConfigured:d.webhookConfigured,limits:limits(d.limits),subscriptionStatus:string(d.subscriptionStatus),prices:d.prices.map(v=>{const p=record(v);if(!Number.isSafeInteger(p.amount)||Number(p.amount)<0)throw Error('Invalid price');return {plan:string(p.plan),amount:Number(p.amount),currency:string(p.currency),limits:limits(p.limits)};})};}
export function Billing(){
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();api('workspace/billing',parse,{signal:c.signal}).then(setData).catch(e=>{if(!c.signal.aborted)setError(message(e));});return()=>c.abort();},[]);
 async function action(path:string,plan?:string){setBusy(true);setError('');try{if(path==='refresh'){setData(await api('workspace/billing/refresh',parse,{method:'POST'}));return;}const result=await api(`workspace/billing/${path}`,record,{method:'POST',body:JSON.stringify({plan})});const url=new URL(string(result.url));if(url.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname))throw Error('Unexpected billing redirect');window.location.assign(url.href);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <section className="panel"><h2>Subscription</h2><p>Stripe sandbox — no real payments. Local Ollama has no paid API usage.</p>{error&&<p className="error-banner" role="alert">{error}</p>}{!data&&!error&&<p>Loading plans…</p>}{data&&<><p>Current plan: <strong>{data.limits.plan}</strong> · {data.subscriptionStatus}</p><p>{data.limits.games} games · {data.limits.monthlyAttempts.toLocaleString()} analysis attempts/month · {data.limits.seats} team seats · {data.limits.reportsPerGame} saved reports/game.</p>{!data.enabled&&<p>Billing is disabled.</p>}{data.enabled&&(!data.configured||!data.webhookConfigured)&&<p>Billing setup is incomplete. Configure the sandbox key and webhook listener.</p>}<><div className="cards">{data.prices.map(p=><article className="panel" key={p.plan}><h3>{p.plan}</h3><p>{new Intl.NumberFormat('pl-PL',{style:'currency',currency:p.currency.toUpperCase()}).format(p.amount/100)} / month</p><p>{p.limits.games} games · {p.limits.monthlyAttempts.toLocaleString()} attempts · {p.limits.seats} seats</p><button disabled={busy||!data.enabled||!data.configured||!data.webhookConfigured||!['none','canceled','incomplete_expired'].includes(data.subscriptionStatus)} onClick={()=>void action('checkout',p.plan)}>Choose {p.plan}</button></article>)}</div><button disabled={busy||!data.enabled||!data.configured||!data.webhookConfigured} onClick={()=>void action('portal')}>Manage subscription</button>{' '}<button disabled={busy||!data.enabled||!data.configured||!data.webhookConfigured} onClick={()=>void action('refresh')}>Refresh payment status</button><p className="muted">After returning from Stripe, refresh the status. Access is confirmed on the server; canceling a plan preserves existing data.</p></></>}</section>;
}
