'use client';
import {Billing} from './billing';
import {DataControls} from '@/app/data-controls';
import {useEffect,useState} from 'react';
import {api,message} from '@/lib/api';
import {Workspace,parseWorkspace,record,string} from '@/lib/workspace';
export default function Settings(){
 const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[role,setRole]=useState('MEMBER'),[token,setToken]=useState(''),[invite,setInvite]=useState(''),[retry,setRetry]=useState(0),[ops,setOps]=useState<Record<string,unknown>|null>(null);
 useEffect(()=>{const c=new AbortController();api('workspace',parseWorkspace,{signal:c.signal}).then(v=>{if(!c.signal.aborted){setData(v);setError('');}}).catch(e=>{if(!c.signal.aborted)setError(message(e));});return()=>c.abort();},[retry]);
 async function action(path:string,body:unknown={},reload=false){setBusy(true);setError('');try{const result=await api(`workspace/${path}`,record,{method:'POST',body:JSON.stringify(body)});if(path==='invites')setToken(string(result.token));if(reload){window.location.reload();return;}setRetry(v=>v+1);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function operations(){try{setOps(await api('workspace/operations',record));setError('');}catch(e){setError(message(e));}}
 return <><div className="eyebrow">WORKSPACE SETTINGS</div><h1>{data?.name??'Settings'}</h1>{error&&<div className="error-banner" role="alert"><p>{error}</p><button onClick={()=>setRetry(v=>v+1)}>Reload settings</button></div>}{!data&&!error&&<p role="status">Loading workspace…</p>}{data&&<><p>Role: {data.role}. Owners manage membership; admins manage game data; members have read-only access.</p>{!data.accountsEnabled?<section className="panel"><h2>Local workspace</h2><p>Accounts are disabled. Team invitations become available when account mode is configured. Existing local data is never automatically assigned to a new account.</p></section>:<>
 <section className="panel"><h2>Switch workspace</h2>{data.workspaces.map(v=><p key={v.id}>{v.name} · {v.role} <button disabled={busy||v.id===data.id} onClick={()=>void action('switch',{workspaceId:v.id},true)}>{v.id===data.id?'Current':'Switch'}</button></p>)}</section>
 <section className="panel"><h2>Team</h2><ul>{data.members.map(v=><li key={v.id}>{v.email} · {v.role}{data.role==='OWNER'&&v.role!=='OWNER'&&<> <button disabled={busy} onClick={()=>void action(`members/${v.id}/role`,{role:v.role==='ADMIN'?'MEMBER':'ADMIN'})}>{v.role==='ADMIN'?'Make read-only':'Make admin'}</button> <button disabled={busy} onClick={()=>void action(`members/${v.id}/remove`)}>Remove access</button></>}</li>)}</ul></section>
 {data.role==='OWNER'&&<section className="panel"><h2>Invite a teammate</h2><p>Invitations are not emailed automatically. Share the one-time token privately with the named email owner; it expires after seven days. Owner access cannot be granted here.</p><form className="filters" onSubmit={e=>{e.preventDefault();void action('invites',{email,role});}}><div><label htmlFor="invite-email">Teammate email</label><input id="invite-email" type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></div><div><label htmlFor="invite-role">Role</label><select id="invite-role" value={role} onChange={e=>setRole(e.target.value)}><option value="MEMBER">Read-only member</option><option value="ADMIN">Admin</option></select></div><button disabled={busy}>Create invitation</button></form>{token&&<div><label htmlFor="created-token">One-time invitation token</label><input id="created-token" readOnly value={token}/><p className="muted">Shown only after creation. Revoke the invitation if it is shared with the wrong person.</p></div>}<ul>{data.invites.map(v=><li key={v.id}>{v.email} · {v.role} · expires {v.expires_at} <button disabled={busy} onClick={()=>void action(`invites/${v.id}/revoke`)}>Revoke</button></li>)}</ul></section>}
 <section className="panel"><h2>Accept an invitation</h2><form onSubmit={e=>{e.preventDefault();void action('invites/accept',{token:invite},true);}}><label htmlFor="accept-token">Invitation token</label><input id="accept-token" required minLength={43} maxLength={43} value={invite} onChange={e=>setInvite(e.target.value)} autoComplete="off"/><button disabled={busy}>Join workspace</button></form><p className="muted">Sign in using the email named in the invitation. Your own workspace remains available after joining.</p></section></>}
 {data.role!=='MEMBER'&&<section className="panel"><h2>Operations</h2><button onClick={()=>void operations()}>Load recent jobs</button>{ops&&Object.entries(ops).map(([kind,value])=><div key={kind}><h3>{kind}</h3>{Array.isArray(value)&&value.length===0?<p>No jobs recorded.</p>:<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(value,null,2)}</pre>}</div>)}<p className="muted">Latest 50 imports and analysis jobs in this workspace. Failure messages are preserved for investigation.</p></section>}
 {data.role==='OWNER'&&<Billing/>}
 <DataControls owner={data.role==='OWNER'} accounts={data.accountsEnabled}/>
 </>}</>;
}
