'use client';
import {useEffect,useState} from 'react';
import {api,message} from '@/lib/api';
import {record,string} from '@/lib/workspace';
type Policy={enabled:boolean;intervalHours:number;analyzeLocal:boolean;weeklyReport:boolean;phase:string;nextSyncAt:string|null;lastError:string|null;workerEnabled:boolean};
function parse(v:unknown):Policy{const d=record(v);for(const k of ['enabled','analyzeLocal','weeklyReport','workerEnabled'])if(typeof d[k]!=='boolean')throw Error('Invalid schedule.');if(typeof d.intervalHours!=='number'||d.intervalHours<1||d.intervalHours>168)throw Error('Invalid interval.');return {enabled:d.enabled as boolean,intervalHours:d.intervalHours,analyzeLocal:d.analyzeLocal as boolean,weeklyReport:d.weeklyReport as boolean,phase:string(d.phase),nextSyncAt:d.nextSyncAt===null?null:string(d.nextSyncAt),lastError:d.lastError===null?null:string(d.lastError),workerEnabled:d.workerEnabled as boolean};}
export function AutomationPanel({id}:{id:string}){
 const [policy,setPolicy]=useState<Policy|null>(null),[items,setItems]=useState<{id:string;title:string;message:string;created:string;unread:boolean}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[notice,setNotice]=useState('');
 useEffect(()=>{const c=new AbortController();Promise.all([api(`games/${id}/automation`,parse,{signal:c.signal}),api(`games/${id}/notifications`,v=>{if(!Array.isArray(v))throw Error('Invalid notifications.');return v.map(v=>{const d=record(v);return {id:string(d.id),title:string(d.title),message:string(d.message),created:string(d.created_at),unread:d.read_at===null};});},{signal:c.signal})]).then(([p,n])=>{if(!c.signal.aborted){setPolicy(p);setItems(n);setError('');}}).catch(e=>{if(!c.signal.aborted)setError(message(e));});return()=>c.abort();},[id,retry]);
 async function save(){if(!policy)return;setBusy(true);setError('');try{setPolicy(await api(`games/${id}/automation`,parse,{method:'POST',body:JSON.stringify({enabled:policy.enabled,intervalHours:policy.intervalHours,analyzeLocal:policy.analyzeLocal,weeklyReport:policy.weeklyReport})}));setNotice('Schedule saved.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function read(){try{await api(`games/${id}/notifications/read`,v=>v,{method:'POST'});setRetry(v=>v+1);}catch(e){setError(message(e));}}
 return <section className="panel"><h2>Optional automatic processing</h2>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{policy&&<><form onSubmit={e=>{e.preventDefault();void save();}}><label><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/> Enable scheduled work for this game</label><label htmlFor="sync-interval">Import interval (hours)</label><input id="sync-interval" type="number" min={1} max={168} required value={policy.intervalHours} onChange={e=>setPolicy({...policy,intervalHours:Number(e.target.value)})}/><label><input type="checkbox" checked={policy.analyzeLocal} onChange={e=>setPolicy({...policy,analyzeLocal:e.target.checked})}/> Analyze one local batch after each import, then rebuild issues</label><label><input type="checkbox" checked={policy.weeklyReport} onChange={e=>setPolicy({...policy,weeklyReport:e.target.checked})}/> Save a weekly report</label><button disabled={busy}>Save schedule</button></form><p className="muted">Phase: {policy.phase} · next import: {policy.nextSyncAt??'not scheduled'} · worker {policy.workerEnabled?'enabled':'disabled by server configuration'}. Quotas still apply. Disabling stops new work, not jobs already started. No cloud analysis or email is scheduled.</p>{policy.lastError&&<p className="warning">{policy.lastError}</p>}</>}
 <h3>Recent notifications</h3>{items.length===0?<p>No notifications yet.</p>:<ul>{items.map(v=><li key={v.id}><strong>{v.unread?'Unread · ':''}{v.title}</strong><p>{v.message}</p><small>{v.created}</small></li>)}</ul>}<button onClick={()=>void read()}>Mark notifications read</button><button onClick={()=>setRetry(v=>v+1)}>Refresh schedule and notifications</button></section>;
}
