'use client';
import Link from 'next/link';
import {CartesianGrid,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Signals,SignalChange} from '@/lib/comparison-signals';
export function ComparisonSignalsView({data,id,date}:{data:Signals;id:string;date:string}){
 const share=(n:number|null)=>n===null?'Unknown':`${(n*100).toFixed(1)}%`;
 function table(rows:SignalChange[],links:boolean){return <div className="table-scroll issue-table"><table><thead><tr><th>Signal</th><th>Before mentions / share</th><th>After mentions / share</th><th>Change (pp)</th><th>Movement</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td>{links?<Link href={`/games/${id}/issues/${v.id}`}>{v.title}</Link>:v.title}</td><td>{v.before} / {share(v.beforeShare)}</td><td>{v.after} / {share(v.afterShare)}</td><td>{v.changePoints===null?'Unknown':`${v.changePoints>0?'+':''}${v.changePoints.toFixed(2)}`}</td><td>{v.movement.replaceAll('_',' ')}</td></tr>)}</tbody></table></div>;}
 return <><section className="panel"><h2>Review timeline · UTC days</h2><div className="chart-frame"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.daily}><CartesianGrid strokeDasharray="3 3" stroke="#28364b"/><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><ReferenceLine x={date} label="Release date" stroke="#67c9ff"/><Line isAnimationActive={false} name="Imported reviews" dataKey="reviews" stroke="#67c9ff" dot={false}/><Line isAnimationActive={false} name="Recommended" dataKey="recommended" stroke="#4ade80" dot={false}/></LineChart></ResponsiveContainer></div><details><summary>Exact daily counts</summary><div className="table-scroll"><table><thead><tr><th>Date</th><th>Reviews</th><th>Recommended</th></tr></thead><tbody>{data.daily.map(v=><tr key={v.date}><td>{v.date}</td><td>{v.reviews}</td><td>{v.recommended}</td></tr>)}</tbody></table></div></details></section>
 <section className="panel"><h2>Analysis coverage and category changes</h2><p>{data.analyzedBefore} analyzed before · {data.analyzedAfter} analyzed after · {data.provider} / {data.model}</p><p className="muted">Shares divide mentions by successfully analyzed reviews in the same period and current provider version. Partial coverage can distort trends. Rule-based OTHER results are unclassified, not evidence of neutral sentiment.</p>{data.categories.length?table(data.categories,false):<p>No current analysis in these windows. Analyze imported reviews from Processing to populate this view.</p>}</section>
 <section className="panel"><h2>Growing, declining and new issues</h2>{data.snapshot.stale&&<p className="warning">Issue grouping is missing or stale. Rebuild it from Issues before interpreting these results.</p>}{data.issues.length?table(data.issues,true):<p>No matching grouped issues in these windows. This does not mean the game has no problems.</p>}<p className="muted">NEW means first observed in the current grouping after the selected date. DECLINING does not prove a fix. Small samples, incomplete imports and changed analysis coverage affect every comparison.</p></section></>;
}
