'use client';
import {useEffect,useState} from 'react';
import {api,Game,message,parseGames} from '@/lib/api';
export function DataControls({owner,accounts}:{owner:boolean;accounts:boolean}){
 const [games,setGames]=useState<Game[]>([]),[game,setGame]=useState(''),[confirmation,setConfirmation]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState('');
 useEffect(()=>{if(!owner)return;const c=new AbortController();api('games',parseGames,{signal:c.signal}).then(v=>{if(!c.signal.aborted)setGames(v);}).catch(e=>{if(!c.signal.aborted)setError(message(e));});return()=>c.abort();},[owner]);
 async function download(){setBusy(true);setError('');try{const data=await api('workspace/export',v=>v);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');try{link.href=url;link.download='playersignal-workspace.json';document.body.appendChild(link);link.click();}finally{link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function remove(account:boolean){setBusy(true);setError('');setDone('');try{await api(account?'workspace/account/delete':`games/${game}/delete`,v=>v,{method:'POST',body:JSON.stringify({confirmation,password})});setPassword('');setConfirmation('');if(account){window.location.reload();return;}setGames(v=>v.filter(g=>g.id!==game));setGame('');setDone('Game and associated data deleted.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <section className="panel"><h2>Data controls</h2>{error&&<p role="alert">{error}</p>}{done&&<p role="status">{done}</p>}{owner&&<><button disabled={busy} onClick={()=>void download()}>Export workspace JSON</button><p className="muted">Up to 5,000 reviews / 10 MiB, including saved reports and preferences. Excludes passwords, session/invite tokens, raw reviewer payloads, classification history and job logs.</p><label htmlFor="delete-game">Game to permanently remove</label><select id="delete-game" value={game} onChange={e=>{setGame(e.target.value);setConfirmation('');}}><option value="">Select a game</option>{games.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></>}
 <p className="warning">Deletion cannot be undone in the app. Deleting your account also removes your solely owned workspaces and their games, reviews, analyses and reports. Other members must be removed first. Backups and downloaded exports can retain copies.</p><label htmlFor="delete-confirmation">Type {game?`DELETE ${game}`:'DELETE MY ACCOUNT'} to confirm the selected action</label><input id="delete-confirmation" value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/>{accounts&&<><label htmlFor="delete-password">Current account password</label><input id="delete-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></>}
 {owner&&game&&<button disabled={busy||confirmation!==`DELETE ${game}`||(accounts&&!password)} onClick={()=>void remove(false)}>Permanently delete selected game</button>}{accounts&&!game&&<button disabled={busy||confirmation!=='DELETE MY ACCOUNT'||!password} onClick={()=>void remove(true)}>Permanently delete my account</button>}
 </section>;
}
