'use client';
import {useEffect,useState} from 'react';
import {api,message} from '@/lib/api';
import {LineChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
type Trend={days:number;analyzedBefore:number;analyzedAfter:number;priorityScore:number;components:Record<string,number>;daily:{date:string;mentions:number}[];snapshot:{stale:boolean};change:{before:number;after:number;changePoints:number|null;movement:string}|null};
function obj(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Invalid issue trend.');return v as Record<string,unknown>;}
function num(v:unknown):number{if(typeof v!=='number'||!Number.isFinite(v))throw Error('Invalid trend value.');return v;}
function text(v:unknown):string{if(typeof v!=='string')throw Error('Invalid trend text.');return v;}
function parse(v:unknown):Trend{const d=obj(v),s=obj(d.snapshot),parts=obj(d.components);if(!Array.isArray(d.daily)||typeof s.stale!=='boolean')throw Error('Invalid trend.');const c=d.change===null?null:obj(d.change);return {days:num(d.days),analyzedBefore:num(d.analyzedBefore),analyzedAfter:num(d.analyzedAfter),priorityScore:num(d.priorityScore),components:Object.fromEntries(Object.entries(parts).map(([k,v])=>[k,num(v)])),snapshot:{stale:s.stale},daily:d.daily.map(v=>{const row=obj(v);return {date:text(row.date),mentions:num(row.mentions)};}),change:c?{before:num(c.before),after:num(c.after),changePoints:c.changePoints===null?null:num(c.changePoints),movement:text(c.movement)}:null};}
const statuses=['OPEN','WATCHING','IMPROVING','RESOLVED','IGNORED'];
function state(v:unknown):string{const s=obj(v).status;if(typeof s!=='string'||!statuses.includes(s))throw Error('Invalid workflow state.');return s;}
export function IssueInsights({id,issue}:{id:string;issue:string}){
 const [data,setData]=useState<Trend|null>(null),[status,setStatus]=useState<string|null>(null),[days,setDays]=useState('30'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();Promise.all([api(`games/${id}/issues/${issue}/trend?days=${days}`,parse,{signal:c.signal}),api(`games/${id}/issues/${issue}/workflow`,state,{signal:c.signal})]).then(([d,s])=>{if(!c.signal.aborted){setData(d);setStatus(s);setError('');}}).catch(e=>{if(!c.signal.aborted)setError(message(e));});return()=>c.abort();},[id,issue,days,retry]);
 async function save(next:string){setBusy(true);try{setStatus(await api(`games/${id}/issues/${issue}/workflow`,state,{method:'POST',body:JSON.stringify({status:next})}));setError('');}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <section className="panel"><h2>Issue trend and workflow</h2><div className="filters"><div><label htmlFor="issue-window">Days per period</label><select id="issue-window" value={days} onChange={e=>{setDays(e.target.value);setData(null);}}>{[7,30,90].map(d=><option key={d} value={d}>{d} days</option>)}</select></div><div><label htmlFor="issue-status">Investigation status</label><select id="issue-status" disabled={busy||status===null} value={status??'OPEN'} onChange={e=>void save(e.target.value)}>{statuses.map(v=><option key={v}>{v}</option>)}</select></div></div><p className="muted">Status is a manual workspace decision, not a model verdict. WATCHING marks the issue for follow-up. The status survives regrouping when category and normalized title remain unchanged.</p>{error&&<p role="alert">{error}</p>}{data?<>{data.snapshot.stale&&<p className="warning">Grouping is stale. Rebuild issues before interpreting this trend.</p>}<p>Analyzed denominators: {data.analyzedBefore} before / {data.analyzedAfter} after. {data.change?`${data.change.before} → ${data.change.after} mentions · ${data.change.changePoints===null?'No baseline':data.change.changePoints.toFixed(2)+' pp'} · ${data.change.movement}`:'No mentions in these periods.'}</p><div className="chart-frame"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.daily}><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Line isAnimationActive={false} name="Current-version mentions" dataKey="mentions" stroke="#67c9ff" dot={false}/></LineChart></ResponsiveContainer></div><details><summary>Exact values and priority calculation · {data.priorityScore.toFixed(1)} / 100</summary><p className="muted">Weighted mention share (35), increasing share (25), negative ratio (20), average extraction severity (10), recency (10). Priority is zero when the after period has no mentions. This is a heuristic investigation score.</p><ul>{Object.entries(data.components).map(([k,v])=><li key={k}>{k}: {v.toFixed(2)}</li>)}</ul><div className="table-scroll"><table><thead><tr><th>Date (UTC)</th><th>Mentions</th></tr></thead><tbody>{data.daily.map(v=><tr key={v.date}><td>{v.date}</td><td>{v.mentions}</td></tr>)}</tbody></table></div></details></>:!error&&<p role="status">Loading trend…</p>}<button onClick={()=>setRetry(v=>v+1)}>Refresh trend and status</button></section>;
}
