'use client';
import {useEffect,useState} from 'react';
import {api,message} from '@/lib/api';
import {record,string} from '@/lib/workspace';
export function ReportSharing({game,report}:{game:string;report:string}){
 const [active,setActive]=useState(false),[expires,setExpires]=useState<string|null>(null),[days,setDays]=useState('7'),[confirmed,setConfirmed]=useState(false),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function parse(v:unknown){const d=record(v);if(typeof d.active!=='boolean')throw Error('Invalid share state.');return {active:d.active,expiresAt:d.expiresAt===null?null:string(d.expiresAt)};}
 useEffect(()=>{const c=new AbortController();api(`games/${game}/reports/${report}/share`,parse,{signal:c.signal}).then(v=>{if(!c.signal.aborted){setActive(v.active);setExpires(v.expiresAt);}}).catch(e=>{if(!c.signal.aborted)setError(message(e));});return()=>c.abort();},[game,report]);
 async function create(){setBusy(true);setError('');try{const v=await api(`games/${game}/reports/${report}/share`,v=>{const d=record(v);return {token:string(d.token),expiresAt:string(d.expiresAt)};},{method:'POST',body:JSON.stringify({days:Number(days),confirmation:confirmed?'SHARE REPORT':''})});setUrl(`${window.location.origin}/shared/${v.token}`);setActive(true);setExpires(v.expiresAt);setConfirmed(false);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function revoke(){setBusy(true);setError('');try{await api(`games/${game}/reports/${report}/share/revoke`,parse,{method:'POST'});setActive(false);setUrl('');}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <section className="panel"><h2>Share this report</h2><p>Owner only. Anyone with the link can read this snapshot’s game name, dates, summary and quoted reviews. Other workspace data stays private. A new link invalidates the previous one.</p><p>Status: {active?'shared':'private'}{expires?` · expires ${expires}`:''}. Revoking a link cannot remove copies already downloaded.</p><label htmlFor="share-days">Link lifetime</label><select id="share-days" value={days} onChange={e=>setDays(e.target.value)}>{[1,7,30].map(v=><option key={v} value={v}>{v} days</option>)}</select><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Allow anyone with this link to read this report</label><button disabled={busy||!confirmed} onClick={()=>void create()}>Create / replace link</button><button disabled={busy||!active} onClick={()=>void revoke()}>Revoke link</button>{url&&<p><label htmlFor="share-url">Copy this link now</label><input id="share-url" readOnly value={url} onFocus={e=>e.target.select()}/><small>Localhost links work only on this computer until hosting is configured.</small></p>}{error&&<p role="alert">{error}</p>}</section>;
}
