'use client';
import {useEffect,useState} from 'react';
import {api,message} from '@/lib/api';
import {record} from '@/lib/workspace';
type Policy={enabled:boolean;reviewDays:number;reportDays:number;notificationDays:number;workerEnabled:boolean};
function parse(v:unknown):Policy{const d=record(v);if(typeof d.enabled!=='boolean'||typeof d.workerEnabled!=='boolean'||typeof d.reviewDays!=='number'||typeof d.reportDays!=='number'||typeof d.notificationDays!=='number')throw Error('Invalid retention policy.');return {enabled:d.enabled,reviewDays:d.reviewDays,reportDays:d.reportDays,notificationDays:d.notificationDays,workerEnabled:d.workerEnabled};}
export function RetentionPanel({id}:{id:string}){
 const [policy,setPolicy]=useState<Policy|null>(null),[preview,setPreview]=useState<string|null>(null),[confirmation,setConfirmation]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();api(`games/${id}/retention`,parse,{signal:c.signal}).then(v=>{if(!c.signal.aborted)setPolicy(v);}).catch(e=>{if(!c.signal.aborted)setError(message(e));});return()=>c.abort();},[id]);
 function change(key:'reviewDays'|'reportDays'|'notificationDays',value:number){if(policy)setPolicy({...policy,[key]:value});setPreview(null);setConfirmation(false);}
 async function inspect(){if(!policy)return;setBusy(true);setError('');try{setPreview(await api(`games/${id}/retention/preview`,v=>{const d=record(v);if(['reviews','reports','readNotifications'].some(k=>typeof d[k]!=='number'))throw Error('Invalid preview.');return `${d.reviews} reviews (and their analyses), ${d.reports} reports (and shared links), ${d.readNotifications} read notifications currently qualify.`;},{method:'POST',body:JSON.stringify(policy)}));}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function save(enabled:boolean){if(!policy)return;setBusy(true);setError('');try{setPolicy(await api(`games/${id}/retention`,parse,{method:'POST',body:JSON.stringify({...policy,enabled,confirmation:enabled&&confirmation?'ENABLE RETENTION':''})}));setNotice(enabled?'Retention enabled. The next worker pass can permanently remove matching data.':'Retention disabled.');setConfirmation(false);setPreview(null);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <section className="panel"><h2>Data retention · owner only</h2><p>Automatic deletion is disabled by default. Reviews are aged by their Steam creation date, reports and read notifications by creation date. Unread notifications remain. Removing reviews clears issue grouping; rebuild it afterwards. Saved reports may retain older quotes until separately removed. Later imports can reintroduce old reviews.</p>{policy&&<><p>Status: {policy.enabled?'enabled':'disabled'} · scheduler {policy.workerEnabled?'enabled':'disabled by server configuration'}</p>{(['reviewDays','reportDays','notificationDays'] as const).map(key=><div key={key}><label htmlFor={key}>{key==='reviewDays'?'Keep reviews':key==='reportDays'?'Keep reports':'Keep read notifications'}</label><select id={key} value={policy[key]} onChange={e=>change(key,Number(e.target.value))}>{(key==='reviewDays'?[0,90,180,365]:key==='reportDays'?[0,30,90,180,365]:[30,90,180,365]).map(v=><option key={v} value={v}>{v===0?'Until manually deleted':`${v} days`}</option>)}</select></div>)}<button disabled={busy} onClick={()=>void inspect()}>Preview deletions</button>{preview&&<p role="status">{preview} Counts can change before the daily deletion pass.</p>}<label><input type="checkbox" disabled={!preview} checked={confirmation} onChange={e=>setConfirmation(e.target.checked)}/> Permanently delete matching data automatically; I have exported anything I need</label><button disabled={busy||!preview||!confirmation} onClick={()=>void save(true)}>Enable / update retention</button><button disabled={busy||!policy.enabled} onClick={()=>void save(false)}>Disable retention</button></>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
