'use client';
import {useState} from 'react';
import {Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Day} from '@/lib/overview';
import {Button} from '@/components/ui/button';
const tooltip={background:'#162235',border:'1px solid #26364D',borderRadius:6,color:'#E8EEF7'};
export function ReviewChart({daily}:{daily:Day[]}){
 const [view,setView]=useState<'volume'|'ratio'>('volume');const rows=daily.map(d=>({...d,label:d.date.slice(5),positivePercent:d.recommended+d.notRecommended===0?null:Math.round(1000*d.recommended/(d.recommended+d.notRecommended))/10}));
 return <><div className="chart-switch" role="group" aria-label="Chart metric"><Button variant={view==='volume'?'secondary':'ghost'} size="sm" aria-pressed={view==='volume'} onClick={()=>setView('volume')}>Review volume</Button><Button variant={view==='ratio'?'secondary':'ghost'} size="sm" aria-pressed={view==='ratio'} onClick={()=>setView('ratio')}>Recommended %</Button></div><div className="chart-frame" role="img" aria-label={view==='volume'?'Daily recommended and not recommended review counts. Exact values in the data table below.':'Daily recommendation percentage. Gaps mean no reviews. Exact values below.'}><ResponsiveContainer width="100%" height="100%" minWidth={0}>
 {view==='volume'?<BarChart data={rows} accessibilityLayer><CartesianGrid vertical={false} stroke="#26364D"/><XAxis dataKey="label" stroke="#94A3B8" tickLine={false} minTickGap={28}/><YAxis allowDecimals={false} stroke="#94A3B8" tickLine={false} width={36}/><Tooltip contentStyle={tooltip} cursor={{fill:'#162235'}}/><Bar dataKey="recommended" name="Recommended" stackId="reviews" fill="#46D39A" isAnimationActive={false}/><Bar dataKey="notRecommended" name="Not recommended" stackId="reviews" fill="#72839D" isAnimationActive={false}/></BarChart>:<LineChart data={rows} accessibilityLayer><CartesianGrid vertical={false} stroke="#26364D"/><XAxis dataKey="label" stroke="#94A3B8" minTickGap={28}/><YAxis domain={[0,100]} unit="%" stroke="#94A3B8" width={48}/><Tooltip contentStyle={tooltip}/><Line type="linear" dataKey="positivePercent" name="Recommended %" stroke="#47B5FF" strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart>}
 </ResponsiveContainer></div><div className="chart-legend"><span><i className="legend-positive"/>Recommended</span>{view==='volume'&&<span><i className="legend-negative"/>Not recommended</span>}</div><details className="chart-data"><summary>Exact daily values (UTC)</summary><div className="table-scroll"><table><thead><tr><th>Date</th><th>Recommended</th><th>Not recommended</th><th>Recommended %</th></tr></thead><tbody>{rows.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.recommended}</td><td>{d.notRecommended}</td><td>{d.positivePercent===null?'No reviews':`${d.positivePercent}%`}</td></tr>)}</tbody></table></div></details></>;
}
export function CategoryChart({categories}:{categories:{category:string;count:number}[]}){const total=categories.reduce((sum,c)=>sum+c.count,0);return <div className="category-bars">{categories.map(c=><div key={c.category}><div><span>{c.category.replaceAll('_',' ')}</span><strong>{c.count} <small>· {Math.round(c.count/total*100)}%</small></strong></div><div className="category-track"><div style={{width:`${100*c.count/Math.max(...categories.map(c=>c.count))}%`}}/></div></div>)}<p className="muted">{total} current successful analyses in this period. One primary category per review.</p></div>;}
