'use client';
import Link from 'next/link';
import {ArrowDownToLine,ArrowUpRight,Check,ChevronRight,RefreshCw,MessageSquareText,Layers3,Activity,ThumbsUp} from 'lucide-react';
import dynamic from 'next/dynamic';
import {Overview,percent,change} from '@/lib/overview';
import {growth} from '@/lib/issues';
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
const ReviewChart=dynamic(()=>import('./charts').then(m=>m.ReviewChart),{ssr:false,loading:()=> <div className="chart-frame skeleton" aria-label="Loading chart"/>});
const CategoryChart=dynamic(()=>import('./charts').then(m=>m.CategoryChart),{ssr:false});
export function OverviewDashboard({data:d,onSync,busy=false}:{data:Overview;onSync:()=>void;busy?:boolean}){
 const demo=d.mode==='SYNTHETIC_DEMO',root=demo?'/demo':`/games/${d.game.id}`,counts=d.analysis.counts,run=d.ingestion;
 const period=`${new Date(d.periodStart).toLocaleDateString(undefined,{timeZone:"UTC"})} – ${new Date(d.asOf).toLocaleDateString(undefined,{timeZone:"UTC"})}`;
 const processing=demo?'/demo':`${root}/processing`;
 return <><div className="page-heading overview-heading"><div><div className="eyebrow">{demo?'SYNTHETIC WORKSPACE':'GAME OVERVIEW'}</div><h1>{d.game.name}</h1><p className="muted">{demo?'Ten invented reviews. No live API calls or database writes.':`Steam App ${d.game.steamAppId} · Updated ${new Date(d.asOf).toLocaleTimeString()}`}</p></div>{demo?<span className="badge demo-badge">DEMO DATA</span>:<Button onClick={onSync} disabled={busy||run?.status==='RUNNING'}><RefreshCw size={16}/>{busy?'Starting…':run?.status==='RUNNING'?'Importing…':run?.status==='PARTIAL'||run?.status==='FAILED'?'Resume import':'Sync reviews'}</Button>}</div>
 <div className="overview-toolbar"><nav className="range-tabs" aria-label="Overview period">{[7,30,90].map(days=><Link key={days} href={`${root}/overview?days=${days}`} aria-current={d.days===days?'page':undefined}>{days} days</Link>)}</nav><span className="muted">{period} · UTC</span></div>
 {!demo&&<div className="data-notice"><ArrowDownToLine size={16}/><span>{run?.status==='PARTIAL'?'Partial import — more reviews are available.':run?.status==='FAILED'?'Last import failed — saved reviews remain available.':run?.status==='RUNNING'?'Import in progress — values will refresh.':run?'Imported sample — Steam coverage may be incomplete.':'No import yet — sync to collect reviews.'} Comparisons describe only the imported sample.</span><Link href={processing}>Processing <ChevronRight size={14}/></Link></div>}
 <div className="metric-grid">
 <Metric label={`Reviews · ${d.days} days`} value={d.metrics.reviews.toLocaleString()} note={`${change(d.metrics.reviewChangePercent)} · ${d.metrics.previousReviews} → ${d.metrics.reviews} reviews`} icon={<MessageSquareText size={18}/>}/>
 <Metric label="Recommended · selected period" value={percent(d.metrics.positiveRatio)} note={d.metrics.positiveChangePoints===null?`${d.metrics.recommended} of ${d.metrics.reviews} reviews`:`${change(d.metrics.positiveChangePoints,' pp')} · ${d.metrics.recommended}/${d.metrics.reviews}`} icon={<ThumbsUp size={18}/>}/>
 <Metric label="Analyzed · all imported" value={`${counts.succeeded.toLocaleString()} / ${d.imported.toLocaleString()}`} note={`${counts.pending} pending · ${counts.failed} failed · ${counts.skipped} skipped`} icon={<Activity size={18}/>} href={processing}/>
 <Metric label="High severity · issue snapshot" value={d.issues.snapshot.builtAt&&counts.succeeded>0?String(d.highSeverityIssues):'—'} note={counts.succeeded===0?'Waiting for review analysis':d.issues.snapshot.builtAt?`${d.issues.total} total issues${d.issues.snapshot.stale?' · Outdated snapshot':''}`:'Rebuild issues after analysis'} icon={<Layers3 size={18}/>} href={`${root}/issues${demo?'':'?minSeverity=75'}`}/>
 </div>
 <div className="dashboard-grid"><Card className="chart-card"><CardHeader><CardTitle><h2>Player recommendations</h2></CardTitle><CardDescription>Daily volume and recommendation rate · {d.days}-day rolling window. First and last UTC days may be partial.</CardDescription></CardHeader><CardContent>{d.metrics.reviews>0?<ReviewChart daily={d.daily}/>:<Empty title="No reviews in this period" text={d.imported?'Try a longer range or import more reviews.':'Start an import to see player recommendations.'} href={processing} action="View processing"/>}</CardContent></Card>
 <Card><CardHeader><CardTitle><h2>Feedback categories</h2></CardTitle><CardDescription>Current classifications · selected period</CardDescription></CardHeader><CardContent>{d.categories.length?<CategoryChart categories={d.categories}/>:<Empty title="Classification is waiting" text={d.analysis.available?'Analyze the imported reviews to reveal recurring feedback themes.':'Configure OpenAI on the backend to analyze real reviews. The synthetic demo works without a key.'} href={demo?'/demo':processing} action="View analysis status"/>}</CardContent></Card></div>
 <div className="dashboard-grid lower-grid"><Card><CardHeader><div className="card-title-row"><CardTitle><h2>Issues to investigate</h2></CardTitle><Link href={`${root}/issues`}>All issues <ArrowUpRight size={14}/></Link></div><CardDescription>{d.issues.snapshot.builtAt?`All imported dates · Snapshot ${new Date(d.issues.snapshot.builtAt).toLocaleString()}. Trends use that snapshot’s two 7-day windows.`:'Waiting for an issue snapshot.'}</CardDescription></CardHeader><CardContent>{d.issues.snapshot.stale&&d.issues.snapshot.builtAt&&<p className="warning">Analyses changed. Rebuild issues to refresh these results.</p>}{d.issues.items.length?<div className="ranked-issues">{d.issues.items.map((issue,i)=><Link key={issue.id} href={demo?'/demo/issues':`${root}/issues/${issue.id}`}><span className="rank">{String(i+1).padStart(2,'0')}</span><div><strong>{issue.title}</strong><span>{issue.metrics.mentionCount} mentions · {issue.category.replaceAll('_',' ')} · {growth(issue.metrics)}</span><small>{issue.metrics.recentMentions} recent / {issue.metrics.previousMentions} previous mentions</small></div><span className={`severity-tag ${issue.metrics.severityScore>=75?'severity-high':''}`}>{issue.metrics.severityScore>=75?'HIGH':'LOWER'}</span></Link>)}</div>:<Empty title={counts.succeeded?'No grouped issues yet':'Evidence comes first'} text={counts.succeeded?'Rebuild clusters from current actionable analyses.':'Issues will appear after reviews have been analyzed and grouped.'} href={`${root}/issues`} action="Open issues"/>}</CardContent></Card>
 <Card><CardHeader><CardTitle><h2>Processing coverage</h2></CardTitle><CardDescription>Actual pipeline state · all imported reviews</CardDescription></CardHeader><CardContent><ol className="pipeline"><li><span className="step-icon"><Check size={14}/></span><div><strong>Game connected</strong><span>{d.game.name}</span></div></li><li><span className="step-icon">2</span><div><strong>{d.imported.toLocaleString()} reviews imported</strong><span>{demo?'Synthetic fixtures':run?`Latest run: ${run.status}`:'Not started'}</span></div></li><li><span className="step-icon">3</span><div><strong>{counts.succeeded.toLocaleString()} reviews analyzed</strong><span>{demo?'Deterministic fixtures':d.analysis.available?`${counts.running} running · ${counts.pending} pending`:'OpenAI not configured'}</span></div></li><li><span className="step-icon">4</span><div><strong>{d.issues.total} issues grouped</strong><span>{d.issues.snapshot.builtAt?(d.issues.snapshot.stale?'Needs rebuild':'Snapshot available'):'Waiting for analysis'}</span></div></li></ol><Button asChild variant="secondary"><Link href={processing}>Inspect processing <ChevronRight size={14}/></Link></Button></CardContent></Card></div>
 <p className="dashboard-footnote">Recommendations are Steam player votes, not AI sentiment. Classification and lexical groups are suggestions backed by review text; they do not establish technical root causes.</p>
 </>;
}
function Metric({label,value,note,icon,href}:{label:string;value:string;note:string;icon:React.ReactNode;href?:string}){const content=<><div><span>{label}</span>{icon}</div><strong>{value}</strong><p>{note}</p></>;return href?<Link className="metric-card" href={href}>{content}</Link>:<div className="metric-card">{content}</div>;}
function Empty({title,text,href,action}:{title:string;text:string;href:string;action:string}){return <div className="empty-state"><Layers3 size={24}/><h3>{title}</h3><p>{text}</p><Link href={href}>{action} →</Link></div>;}
export function OverviewSkeleton(){return <div role="status" aria-label="Loading overview"><div className="skeleton skeleton-title"/><div className="metric-grid">{[0,1,2,3].map(i=><div key={i} className="skeleton skeleton-metric"/>)}</div><div className="dashboard-grid"><div className="skeleton skeleton-chart"/><div className="skeleton skeleton-chart"/></div></div>;}
