// @vitest-environment jsdom
import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {OverviewWorkspace} from './overview-workspace';
import {parseOverview} from '@/lib/overview';
vi.mock('next/dynamic',()=>({default:()=>function Chart(){return <div>Chart region</div>;}}));
const fixture={mode:'LIVE',game:{id:'test-game',steamAppId:620,name:'Test game',headerImageUrl:null,createdAt:'2026-10-01T12:00:00Z'},days:30,periodStart:'2026-09-01T12:00:00Z',asOf:'2026-10-01T12:00:00Z',imported:0,metrics:{reviews:0,recommended:0,positiveRatio:null,previousReviews:0,previousPositiveRatio:null,reviewChangePercent:null,positiveChangePoints:null},daily:[],categories:[],analysis:{available:false,provider:'openai',model:'test',promptVersion:'v1',maxReviewsPerRun:25,counts:{total:0,pending:0,running:0,succeeded:0,skipped:0,failed:0},latestRun:null},ingestion:null,issues:{snapshot:{builtAt:null,algorithm:'lexical-centroid-v1',threshold:.72,clusteredReviews:0,eligibleReviews:0,stale:true},items:[],page:0,size:5,total:0},highSeverityIssues:0};
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('shows honest empty states and shareable range links',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json(fixture)));render(<OverviewWorkspace id="test-game"/>);await screen.findByRole('heading',{name:'Test game'});expect(screen.getByText('No reviews in this period')).toBeTruthy();expect(screen.getByText('Classification is waiting')).toBeTruthy();expect(screen.getByRole('link',{name:'90 days'}).getAttribute('href')).toBe('/games/test-game/overview?days=90');expect(screen.getAllByText('—')).toHaveLength(2);});
it('recovers from a failed initial load through the retry button',async()=>{const fetch=vi.fn().mockResolvedValueOnce(Response.json({message:'Backend unavailable'},{status:503})).mockResolvedValueOnce(Response.json(fixture));vi.stubGlobal('fetch',(url:RequestInfo|URL,init?:RequestInit)=>String(url)==='/api/auth/session'?Promise.resolve(Response.json({enabled:false,user:null,csrfToken:null})):fetch(url,init));render(<OverviewWorkspace id="test-game"/>);await screen.findByRole('alert');await userEvent.click(screen.getByRole('button',{name:'Retry loading'}));await screen.findByRole('heading',{name:'Test game'});expect(screen.queryByRole('alert')).toBeNull();expect(fetch).toHaveBeenCalledTimes(2);});
it('preserves loaded values and exposes sync failure',async()=>{const fetch=vi.fn().mockResolvedValueOnce(Response.json(fixture)).mockResolvedValueOnce(Response.json({message:'Steam unavailable'},{status:502}));vi.stubGlobal('fetch',(url:RequestInfo|URL,init?:RequestInit)=>String(url)==='/api/auth/session'?Promise.resolve(Response.json({enabled:false,user:null,csrfToken:null})):fetch(url,init));render(<OverviewWorkspace id="test-game"/>);await screen.findByRole('heading',{name:'Test game'});await userEvent.click(screen.getByRole('button',{name:'Sync reviews'}));await screen.findByText('Steam unavailable');expect(screen.getByRole('heading',{name:'Test game'})).toBeTruthy();expect(fetch.mock.calls[1][1].method).toBe('POST');});
it('sends live sync and disables it while the import runs',async()=>{const run={id:'run',status:'RUNNING',fetched:0,inserted:0,updated:0,startedAt:'2026-10-01T12:00:00Z',finishedAt:null,error:null};const fetch=vi.fn().mockResolvedValueOnce(Response.json(fixture)).mockResolvedValueOnce(Response.json(run)).mockImplementation(()=>Promise.resolve(Response.json({...fixture,ingestion:run})));vi.stubGlobal('fetch',(url:RequestInfo|URL,init?:RequestInit)=>String(url)==='/api/auth/session'?Promise.resolve(Response.json({enabled:false,user:null,csrfToken:null})):fetch(url,init));render(<OverviewWorkspace id="test-game"/>);await screen.findByRole('heading',{name:'Test game'});await userEvent.click(screen.getByRole('button',{name:'Sync reviews'}));await waitFor(()=>expect((screen.getByRole('button',{name:'Importing…'}) as HTMLButtonElement).disabled).toBe(true));});
it('demo has no mutation control and rejects malformed metrics',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json({...fixture,mode:'SYNTHETIC_DEMO'})));render(<OverviewWorkspace demo/>);await screen.findByText('DEMO DATA');expect(screen.queryByRole('button',{name:'Sync reviews'})).toBeNull();expect(()=>parseOverview({...fixture,metrics:{...fixture.metrics,positiveRatio:5}})).toThrow();});
