'use client';
import {useEffect,useState} from 'react';
import {record,string} from '@/lib/workspace';
import {message} from '@/lib/api';
type Report={gameName:string;periodStart:string;periodEnd:string;createdAt:string;method:string;summary:string[];evidence:{title:string;sourceText:string;steamReviewId:string;model:string}[]};
export function SharedReport({token}:{token:string}){
 const [data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const c=new AbortController();async function load(){try{if(!/^[A-Za-z0-9_-]{43}$/.test(token))throw Error('This report link is unavailable.');const response=await fetch(`/api/shared-reports/${token}`,{cache:'no-store',signal:c.signal,credentials:'omit',referrerPolicy:'no-referrer'});const v=record(await response.json());if(!response.ok)throw Error(typeof v.message==='string'?v.message:'This report is unavailable.');if(!Array.isArray(v.summary)||!Array.isArray(v.evidence))throw Error('Invalid report.');const report={gameName:string(v.gameName),periodStart:string(v.periodStart),periodEnd:string(v.periodEnd),createdAt:string(v.createdAt),method:string(v.method),summary:v.summary.map(string),evidence:v.evidence.map(v=>{const e=record(v);return {title:string(e.title),sourceText:string(e.sourceText),steamReviewId:string(e.steamReviewId),model:string(e.model)};})};if(!c.signal.aborted){setData(report);setError('');}}catch(e){if(!c.signal.aborted){setData(null);setError(message(e));}}}void load();return()=>c.abort();},[token,retry]);
 return <><div className="eyebrow">SHARED REPORT · READ ONLY</div>{error?<section className="panel" role="alert"><h1>Report unavailable</h1><p>{error}</p><button onClick={()=>setRetry(v=>v+1)}>Retry</button></section>:!data?<p role="status">Loading report…</p>:<section className="panel"><h1>{data.gameName}</h1><p>{data.periodStart} – {data.periodEnd} · UTC</p><p>{data.method}</p><ul>{data.summary.map((v,i)=><li key={i}>{v}</li>)}</ul><h2>Preserved review evidence</h2>{data.evidence.map((v,i)=><article key={i}><h3>{v.title}</h3><blockquote>{v.sourceText}</blockquote><p>Steam review #{v.steamReviewId} · {v.model}</p></article>)}<p className="muted">Saved {data.createdAt}. This snapshot may be outdated; changes are not proof of causation.</p><button onClick={()=>window.print()}>Print / save PDF</button></section>}</>;
}
